version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: chatroom
  app:
    image: chat-app-server
    ports:
      - 13000:3000
